{% set name = "namex" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/namex-{{ version }}.tar.gz
  sha256: 32a50f6c565c0bb10aa76298c959507abdc0e850efe085dc38f3440fcb3aa90b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - namex
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fchollet/namex?tab=readme-ov-file
  summary: A simple utility to separate the implementation of your Python package and its public API surface.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Anselmoo
